name: CI Workflow for DDS

on:
  push:
    branches:
      - DDS  
  pull_request:
    branches:
      - DDS  

jobs:
  test-and-sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run coverage

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          sonar-scanner \
            -Dsonar.projectKey=ecoadventure \
            -Dsonar.sources=src \
            -Dsonar.tests=src \
            -Dsonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov-report/lcov.info \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}